/**
 * OpenBuckets API
 * The OpenBuckets web-based tool is a powerful utility that allows users to quickly locate open buckets in cloud storage systems through a simple query. In addition, it provides a convenient way to search for various file types across these open buckets, making it an essential tool for security professionals, researchers, and anyone interested in discovering exposed data. This Postman collection aims to showcase the capabilities of OpenBuckets by providing a set of API requests that demonstrate how to leverage its features. By following this collection, you'll learn how to utilize OpenBuckets to identify open buckets and search for specific file types within them.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@openbuckets.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenBucketsApi);
  }
}(this, function(expect, OpenBucketsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenBucketsApi.FileSearchResultsFilesInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FileSearchResultsFilesInner', function() {
    it('should create an instance of FileSearchResultsFilesInner', function() {
      // uncomment below and update the code to test FileSearchResultsFilesInner
      //var instance = new OpenBucketsApi.FileSearchResultsFilesInner();
      //expect(instance).to.be.a(OpenBucketsApi.FileSearchResultsFilesInner);
    });

    it('should have the property bucketId (base name: "bucketId")', function() {
      // uncomment below and update the code to test the property bucketId
      //var instance = new OpenBucketsApi.FileSearchResultsFilesInner();
      //expect(instance).to.be();
    });

    it('should have the property cloudProvider (base name: "cloudProvider")', function() {
      // uncomment below and update the code to test the property cloudProvider
      //var instance = new OpenBucketsApi.FileSearchResultsFilesInner();
      //expect(instance).to.be();
    });

    it('should have the property fileExtension (base name: "fileExtension")', function() {
      // uncomment below and update the code to test the property fileExtension
      //var instance = new OpenBucketsApi.FileSearchResultsFilesInner();
      //expect(instance).to.be();
    });

    it('should have the property fileName (base name: "fileName")', function() {
      // uncomment below and update the code to test the property fileName
      //var instance = new OpenBucketsApi.FileSearchResultsFilesInner();
      //expect(instance).to.be();
    });

    it('should have the property fileSize (base name: "fileSize")', function() {
      // uncomment below and update the code to test the property fileSize
      //var instance = new OpenBucketsApi.FileSearchResultsFilesInner();
      //expect(instance).to.be();
    });

    it('should have the property fileUrl (base name: "fileUrl")', function() {
      // uncomment below and update the code to test the property fileUrl
      //var instance = new OpenBucketsApi.FileSearchResultsFilesInner();
      //expect(instance).to.be();
    });

    it('should have the property fullPath (base name: "fullPath")', function() {
      // uncomment below and update the code to test the property fullPath
      //var instance = new OpenBucketsApi.FileSearchResultsFilesInner();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new OpenBucketsApi.FileSearchResultsFilesInner();
      //expect(instance).to.be();
    });

    it('should have the property indexedAt (base name: "indexedAt")', function() {
      // uncomment below and update the code to test the property indexedAt
      //var instance = new OpenBucketsApi.FileSearchResultsFilesInner();
      //expect(instance).to.be();
    });

    it('should have the property lastModified (base name: "lastModified")', function() {
      // uncomment below and update the code to test the property lastModified
      //var instance = new OpenBucketsApi.FileSearchResultsFilesInner();
      //expect(instance).to.be();
    });

  });

}));
